try fix ci

diff --git a/.github/workflows/export-pdf-from-svg.yml b/.github/workflows/export-pdf-from-svg.yml
--- a/.github/workflows/export-pdf-from-svg.yml
+++ b/.github/workflows/export-pdf-from-svg.yml
@@ -47,19 +47,51 @@ jobs:
           npm install
           npx -p node@v18-lts -c "npx semantic-release"
 
-      - name: Deploy to GitHub Releases
+    #   - name: Deploy to GitHub Releases
+    #     env:
+    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     shell: bash
+    #     run: |
+    #       if [[ $GITHUB_REF == 'refs/heads/master' || $GITHUB_REF == 'refs/heads/main' ]]; then
+    #         TAG=$(git describe --tags --exact-match HEAD || echo "")
+    #         if [[ -n $TAG ]]; then
+    #           echo "Preparing release $TAG"
+    #           gh release create "$TAG" ./*.pdf --notes "Release $TAG" --clobber
+    #         else
+    #           echo "No tag found for this commit"
+    #         fi
+    #       else
+    #         echo "Deployment not triggered. Current branch: $GITHUB_REF"
+    #       fi
+      - name: Autotag
+        uses: DanySK/semver-autotag-action@0.1.0
+      - name: Deploy
+        if: inputs.publish-enable == 'true'
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            GITHUB_TOKEN: ${{ inputs.token }}
         shell: bash
         run: |
-          if [[ $GITHUB_REF == 'refs/heads/master' || $GITHUB_REF == 'refs/heads/main' ]]; then
-            TAG=$(git describe --tags --exact-match HEAD || echo "")
-            if [[ -n $TAG ]]; then
-              echo "Preparing release $TAG"
-              gh release create "$TAG" ./*.pdf --notes "Release $TAG" --clobber
+            if [[ -z $GITHUB_TOKEN ]]; then
+            echo "No token set, cannot deploy"
+            false
             else
-              echo "No tag found for this commit"
+                if [[ $GITHUB_REF == 'refs/heads/master'
+                    || $GITHUB_REF == 'refs/heads/main'
+                    || $GITHUB_REF == 'refs/heads/default'
+                    || $GITHUB_REF == "refs/tags"*
+                ]]; then
+                    TAG=$(git describe --tags --exact-match HEAD)
+                    echo "Preparing release $TAG"
+                    git tag --delete "$TAG"
+                    git tag "$TAG"
+                    git push --tags && echo "Tag $TAG successfully pushed" || true
+                    gh release create --notes-from-tag "$TAG" || true
+                    while IFS= read -r file; do
+                    pdf="${file%.*}.pdf"
+                    echo "Delivering file $pdf"
+                    gh release upload "$TAG" "$pdf" --clobber
+                    done <<< "$LATEX_SUCCESSES"
+                else
+                    echo "Not running deployment from unknown source: $GITHUB_REF"
+                fi
             fi
-          else
-            echo "Deployment not triggered. Current branch: $GITHUB_REF"
-          fi
